server {
    listen 8083;
    host 127.0.0.1;
    server_name server_a;
    root www;
    index index.html;
    client_max_body_size 10485760;
    error_page 404 www/errors/404.html;

    location / {
		index index.html;
        allow_methods GET POST DELETE;
        autoindex off;
    }

    location /upload {
        allow_methods GET POST DELETE;
        upload_path www/upload/;
        autoindex on;
    }

    location /cgi-bin {
        allow_methods GET POST DELETE;
        cgi_path www/cgi-bin;
        cgi_interpreter /usr/bin/python3;
        cgi_ext .py .php .sh;
    }
}

server {
    listen 8084;
    host 127.0.0.1;
    server_name server_b;
    root www;
    index index.html;
    client_max_body_size 512;
    error_page 404 www/errors/404.html;

    location / {
		index index.html;
        allow_methods GET;
        autoindex off;
    }
}